title: Haiyu Bai
description: Academic website and research portfolio
show_downloads: false
google_analytics: # Add your Google Analytics ID here

# SEO Settings
lang: en
author: Haiyu Bai
keywords: "research, academic, machine learning, data science, publications"

# Academic Links
github_username: haiyu-bai
# orcid_id: 0000-0000-0000-0000
# scholar_id: your-google-scholar-id

# Site Settings
timezone: UTC
encoding: utf-8
markdown: kramdown
highlighter: rouge

# Collections for academic content
collections:
  publications:
    output: true
    permalink: /:collection/:name/