theme: jekyll-theme-minimal
title: Baihaiyu
description: Welcome to my GitHub Pages demo website
show_downloads: false
google_analytics: 

# SEO优化
lang: zh-CN
author: Haiyu Bai
keywords: "portfolio, developer, web development, GitHub Pages"

# 社交媒体链接（可选）
github_username: haiyu-bai
# linkedin_username: haiyu-bai
# twitter_username: haiyu_bai

# 网站设置
timezone: Asia/Shanghai
encoding: utf-8