# Jekyll Configuration for GitHub Pages
title: Haiyu Bai
description: Academic website and research portfolio
show_downloads: false

# SEO Settings
lang: en
author: Haiyu Bai
keywords: "research, academic, machine learning, data science, publications"

# Academic Links
github_username: haiyu-bai
# orcid_id: 0000-0000-0000-0000
# scholar_id: your-google-scholar-id

# Site Settings
timezone: UTC
encoding: utf-8
markdown: kramdown
highlighter: rouge

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Collections for academic content
collections:
  publications:
    output: true
    permalink: /:collection/:name/

# Exclude from processing
exclude:
  - node_modules/
  - .gitignore
  - README.md
  - docs/
  - assets/js/navigation.js
  - assets/js/utils.js
  - components/